-include ../Makefile

linear_search: ## run linear_search
	$(call run,linear_search)

min_linear_search: ## run min_linear_search
	$(call run,min_linear_search)

min_pair: ## run min_pair
	$(call run,min_pair)
