-include ../Makefile

graph: ## run graph
	$(call run,graph)

recursive_dfs: ## run recursive_dfs
	$(call run,recursive_dfs)

queue_bfs: ## run queue_bfs
	$(call run,queue_bfs)

st_path: ## run st_path
	$(call run,st_path)
