-include ../Makefile

linked_list: ## run linked_list
	$(call run,linked_list)

bidirectional_linked_list: ## run bidirectional_linked_list
	$(call run,bidirectional_linked_list)

list_stack: ## run list_stack
	$(call run,list_stack)

slice_stack: ## run slice_stack
	$(call run,slice_stack)

stack: ## run stack
	$(call run,stack)

list_queue: ## run list_queue
	$(call run,list_queue)

slice_queue: ## run slice_queue
	$(call run,slice_queue)

queue: ## run queue
	$(call run,queue)

heap: ## run heap
	$(call run,heap)
