-include ../Makefile

linked_list: ## run linked_list
	$(call run,linked_list)

bidirectional_linked_list: ## run bidirectional_linked_list
	$(call run,bidirectional_linked_list)

stack: ## run stack
	$(call run,stack)

queue: ## run queue
	$(call run,queue)
