-include ../Makefile

frog: ## run frog
	$(call run,frog)

relaxation: ## run relaxation
	$(call run,relaxation)

memo: ## run memo
	$(call run,memo)

knapsack: ## run knapsack
	$(call run,knapsack)

vacation: ## run vacation
	$(call run,vacation)
