-include ../Makefile

euclid: ## run euclid
	$(call run,euclid)

fibonacci: ## run fibonacci
	$(call run,fibonacci)

for: ## run for
	$(call run,for)

memo: ## run memo
	$(call run,memo)

partial_sum: ## run partial_sum
	$(call run,partial_sum)
